package pl.dch.marketplace.session;

import java.util.Arrays;

import io.swagger.v3.oas.models.media.StringSchema;
import io.swagger.v3.oas.models.parameters.HeaderParameter;
import org.springdoc.core.customizers.OperationCustomizer;
import org.springdoc.core.utils.SpringDocUtils;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Makes the OpenAPI document show {@link SessionId} parameters as the required
 * {@code X-Session-Id} header instead of a query object.
 */
@Configuration
class SessionOpenApiConfig {

    static {
        SpringDocUtils.getConfig().addRequestWrapperToIgnore(SessionId.class);
    }

    @Bean
    OperationCustomizer sessionIdHeaderCustomizer() {
        return (operation, handlerMethod) -> {
            boolean usesSession = Arrays.stream(handlerMethod.getMethodParameters())
                    .anyMatch(parameter -> SessionId.class.equals(parameter.getParameterType()));
            if (usesSession) {
                operation.addParametersItem(new HeaderParameter()
                        .name(SessionIdArgumentResolver.HEADER_NAME)
                        .required(true)
                        .description("Anonymous session UUID generated by the browser")
                        .schema(new StringSchema().format("uuid")));
            }
            return operation;
        };
    }
}
