package pl.dch.marketplace.checkout;

import java.net.URI;
import java.util.UUID;

import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RestController;
import pl.dch.marketplace.common.ErrorCode;
import pl.dch.marketplace.common.MarketplaceException;
import pl.dch.marketplace.order.OrderResponse;
import pl.dch.marketplace.payment.PaymentClient;
import pl.dch.marketplace.session.SessionId;

@RestController
@Tag(name = "Checkout")
class CheckoutController {

    static final String IDEMPOTENCY_KEY_HEADER = "Idempotency-Key";

    private final CheckoutService checkoutService;
    private final PaymentReconciliationService reconciliationService;

    CheckoutController(CheckoutService checkoutService, PaymentReconciliationService reconciliationService) {
        this.checkoutService = checkoutService;
        this.reconciliationService = reconciliationService;
    }

    /**
     * Creates an order from the current cart and pays for it. 201 for the request that created the
     * order, 200 with the same order for a repeated request with the same {@code Idempotency-Key}.
     * The order status tells the payment result: PAID, PAYMENT_FAILED or PAYMENT_UNKNOWN.
     */
    @PostMapping("/api/checkout")
    ResponseEntity<OrderResponse> checkout(
            SessionId sessionId,
            @Parameter(in = ParameterIn.HEADER, required = true,
                    description = "UUID generated by the client once per checkout attempt; reused when retrying it")
            @RequestHeader(name = IDEMPOTENCY_KEY_HEADER, required = false) String idempotencyKey,
            @Parameter(in = ParameterIn.HEADER,
                    description = "Dev/test only, forwarded to payment-service when enabled: SUCCESS, DECLINED, SLOW, "
                            + "SERVER_ERROR, SERVER_ERROR_ONCE, SUCCESS_BUT_SLOW_RESPONSE")
            @RequestHeader(name = PaymentClient.SCENARIO_HEADER, required = false) String paymentScenario) {
        CheckoutService.CheckoutResult result =
                checkoutService.checkout(sessionId, parseIdempotencyKey(idempotencyKey), paymentScenario);
        URI location = URI.create("/api/orders/" + result.order().id());
        return result.created()
                ? ResponseEntity.created(location).body(result.order())
                : ResponseEntity.ok().location(location).body(result.order());
    }

    /**
     * Asks payment-service for the result of an order whose payment is unknown or pending and applies it.
     * Idempotent: an order with a final status is returned unchanged.
     */
    @PostMapping("/api/orders/{id}/reconcile-payment")
    OrderResponse reconcilePayment(SessionId sessionId, @PathVariable long id) {
        return reconciliationService.reconcile(sessionId, id);
    }

    private static UUID parseIdempotencyKey(String header) {
        if (header == null || header.isBlank()) {
            throw new MarketplaceException(ErrorCode.MISSING_IDEMPOTENCY_KEY,
                    "Missing required header " + IDEMPOTENCY_KEY_HEADER);
        }
        try {
            return UUID.fromString(header.trim());
        } catch (IllegalArgumentException ex) {
            throw new MarketplaceException(ErrorCode.INVALID_IDEMPOTENCY_KEY,
                    "Header " + IDEMPOTENCY_KEY_HEADER + " must be a UUID");
        }
    }
}
