-- Phase 2: payment integration.
--
-- checkout_idempotency_key: sent by the client (Idempotency-Key header); one key = one checkout attempt
--                           = at most one order per session.
-- payment_idempotency_key:  generated by the marketplace when the order is created and sent to
--                           payment-service on every attempt (including retries) and on reconciliation.
-- Both are nullable only because orders created in Phase 1 (status NEW) have neither.
ALTER TABLE orders
    ADD COLUMN checkout_idempotency_key UUID,
    ADD COLUMN payment_idempotency_key  UUID,
    ADD COLUMN payment_id               VARCHAR(64),
    ADD COLUMN payment_failure_reason   VARCHAR(32);

-- Concurrent duplicate checkouts: the second INSERT waits for the first transaction and then fails
-- on this constraint instead of creating a second order.
ALTER TABLE orders
    ADD CONSTRAINT uk_orders_session_checkout_key UNIQUE (session_id, checkout_idempotency_key);

ALTER TABLE orders
    ADD CONSTRAINT uk_orders_payment_idempotency_key UNIQUE (payment_idempotency_key);

ALTER TABLE orders
    ADD CONSTRAINT ck_orders_status
        CHECK (status IN ('NEW', 'PAYMENT_PENDING', 'PAID', 'PAYMENT_FAILED', 'PAYMENT_UNKNOWN'));

-- Every order that went through the payment flow has both keys; a failure reason exists only for failed payments.
ALTER TABLE orders
    ADD CONSTRAINT ck_orders_payment_keys
        CHECK (status = 'NEW' OR (checkout_idempotency_key IS NOT NULL AND payment_idempotency_key IS NOT NULL));

ALTER TABLE orders
    ADD CONSTRAINT ck_orders_failure_reason
        CHECK ((status = 'PAYMENT_FAILED') = (payment_failure_reason IS NOT NULL));
