package pl.dch.marketplace.product;

import java.math.BigDecimal;

import org.springframework.test.util.ReflectionTestUtils;

/**
 * Builds products for unit tests. The id is normally generated by the database,
 * so it is set via reflection here instead of adding a setter to the entity.
 */
public final class TestProducts {

    private TestProducts() {
    }

    public static Product product(long id, String name, String price, int availableQuantity) {
        Product product = new Product(name, name + " description", new BigDecimal(price), availableQuantity);
        ReflectionTestUtils.setField(product, "id", id);
        return product;
    }
}
